Github Actions ci/cd config to test dependencies & src code automatically, as well as to deploy to npm registry
nebulr-group/nblocks-nestjs pull request #10
Opened 2022-09-13 22:12 UTC by nemanja255

This merge contains config changes for ci/cd

2022-09-13 22:39 UTC, nemanja255 commented
Commit [da6d0da](https://github.com/nebulr-group/nblocks-nestjs/pull/10/commits/da6d0da73d782da100977d01ce2638581bf8cbd0) was amended two times hence the -f flag was used. Having new commit would be redundant.

2022-09-14 12:54 UTC, orr3 requested changes
Nice work man!

2022-09-14 12:54 UTC, orr3 commented on .devcontainer/devcontainer.json
> +				"terminal.integrated.profiles.shell.linux": "/bin/bash"
This doesn't work anymore. Please help fixing this

2022-09-14 12:54 UTC, orr3 commented on .devcontainer/init.sh
> +source $PWD/secrets.env.default
Revert changes

2022-09-14 12:54 UTC, orr3 commented on .devcontainer/init.sh
> +source $PWD/secrets.env.default
But keep it here at the top

2022-09-14 12:54 UTC, orr3 commented on .github/dependabot.yml
> +    target-branch: "master"
Change branch

2022-09-14 12:54 UTC, orr3 commented on .github/workflows/ci-cd.yml
> +          outputs: type=docker,dest=/tmp/nblocks-nestjs.tar
Can we have `nblocks-nestjs` as a variable and reference it everywhere?

2022-09-14 12:54 UTC, orr3 commented on publish.sh
> +#! /bin/sh
Rename file to something better. Don't forget to refactor where this file is suppose to be called from. chmod +x????

2022-09-14 18:51 UTC, merged